name: Create ZIP Archive
on: [push]
jobs:
 build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create report file
      run: date +%s > report.txt
       
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release-${{ github.ref_name }}.zip'
        exclusions: '*.git* ./build/ README.md report.txt'
        
    - name: Move to "build" directory
      run: move /y "D:\a\Samsung-Game-Services-Installer\Samsung-Game-Services-Installer\release-${{ github.ref_name }}.zip" "D:\a\Samsung-Game-Services-Installer\Samsung-Game-Services-Installer\build\"
      shell: cmd
       
    - name: Upload Samsung Game Services Installer ZIP Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: 'release-${{ github.ref_name }}.zip'
        path: 'D:\a\Samsung-Game-Services-Installer\Samsung-Game-Services-Installer\build\release-${{ github.ref_name }}.zip'
        
    - name: Push commit for ZIP archive
      run: |
         git config --global user.name '${{ secrets.git_username }}'
         git config --global user.email '${{ secrets.git_email }}'
         git init
         git add -A
         git commit -am "Create new ZIP archive release"
         git push -u origin ${{ github.ref_name }}
