name: Create ZIP Archive
on: [push]
jobs:
 build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create report file
      run: date +%s > report.txt
       
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release-$GITHUB_REF_NAME.zip'
        exclusions: '*.git* ./build/ README.md report.txt'
        
    - name: Move to "build" directory
      run: move /y D:\a\Samsung-Game-Services-Installer\Samsung-Game-Services-Installer\release-$GITHUB_REF_NAME.zip D:\a\Samsung-Game-Services-Installer\Samsung-Game-Services-Installer\build\
      shell: cmd
    - uses: actions/checkout@v2
    - name: Push commit for ZIP archive
      run: |
         git config --global user.name '${{ secrets.git_username }}'
         git config --global user.email '${{ secrets.git_email }}'
         git init
         git add -A
         git commit -am "Create new ZIP archive release"
         git push -u origin dev
